/**
 * Base de datos local (MOCK) de productos para NovaBox.
 * Cada objeto dentro de este array representa un producto que se mostrará en la tienda.
 * Campos clave:
 * - price: Precio normal o tachado (si hay un min_price menor).
 * - min_price: Precio de oferta o desde donde parte el costo (opcional).
 * - category: Determina en qué sección aparece al filtrar.
 */
const PRODUCTS = [
  {
    "id": "1",
    "name": "Reloj de Pared - Lampara de colroes - Retro de Vinilo",
    "price": 100.0,
    "min_price": 90.0,
    "category": "Decoración / Regalos",
    "brand": "Tema Musical (Piano/Violín)",
    "color": "Negro (Luz RGB)",
    "features": "Reloj analógico decorativo en disco de vinilo cortado con láser. Incluye luces LED RGB.",
    "power": "1 Pila AA (reloj) + Enchufe USB (luz)",
    "instructions": "1. Insertar pila. 2. Colgar en pared. 3. Conectar cable USB para luces.",
    "warnings": "Manejar con cuidado; el acrílico es delicado ante caídas.",
    "fun_fact": "Hechos reciclando o emulando discos de vinilo de 12 pulgadas.",
    "image": "assets/images/productos/oficial/01 - Reloj lampara de vinilo/01 - Reloj lampara de vinilo - 01.jpg"
  },
  {
    "id": "2",
    "name": "Cámara PTZ Solar 4G",
    "price": 550.0,
    "min_price": 450.0,
    "category": "Seguridad / Domótica",
    "brand": "Genérico 4G (Doble Antena)",
    "color": "Blanco",
    "features": "Cámara exterior giratoria (360°) con chip SIM 4G, visión nocturna y panel solar.",
    "power": "Batería interna + Panel Solar",
    "instructions": "1. Insertar chip SIM. 2. Fijar panel en lugar soleado. 3. Descargar App escaneando QR. 4. Emparejar.",
    "warnings": "Asegurar buena cobertura del operador móvil seleccionado.",
    "fun_fact": "Funciona totalmente aislada de la red eléctrica gracias a su panel solar.",
    "image": "assets/images/productos/oficial/02 - Cámara PTZ Solar 4G/02 - Cámara PTZ Solar 4G - 01.jpg"
  },
  {
    "id": "3",
    "name": "Lámpara de Mesa Minimalista LED",
    "price": 90.0,
    "min_price": 90.0,
    "category": "Hogar",
    "brand": "Desk Lamp",
    "color": "Plateado / Acero",
    "features": "Lámpara táctil inalámbrica regulable en intensidad y tono (cálida/fría).",
    "power": "Batería recargable USB-C",
    "instructions": "1. Cargar por USB-C. 2. Toque superior para encender/cambiar tono. 3. Mantener presionado para brillo.",
    "warnings": "No usar cargadores de carga rápida (fast charge) para cuidar la batería.",
    "fun_fact": "Muy popular en terrazas de restaurantes de alta gama por su estética portátil.",
    "image": "assets/images/productos/oficial/03 - Lampara de mesa Minimalista Touch/02 - Lampara de mesa Minimalista Touch - Con caja.jpg"
  },
  {
    "id": "4",
    "name": "Luces LED Calabaza",
    "price": 45.0,
    "min_price": 45.0,
    "category": "Decoración / Regalos",
    "brand": "ME3010 / Solar Flower Lights",
    "color": "Naranja y Negro",
    "features": "Estacas de jardín con calabazas iluminadas por panel solar. Resistentes al agua.",
    "power": "Panel Solar + Batería recargable",
    "instructions": "1. Armar estacas. 2. Encender interruptor ON. 3. Clavar en jardín expuesto al sol.",
    "warnings": "Limpiar el panel solar si se llena de polvo para no perder eficiencia.",
    "fun_fact": "Tienen sensor fotovoltaico: se encienden solas al anochecer y se apagan al amanecer.",
    "image": "assets/images/productos/oficial/04 - Luces LED Calabaza Solares/04 - Luces de calabaza Solar - Prendido.jpg"
  },
  {
    "id": "5",
    "name": "Parlante Bola de Luces Mágica",
    "price": 90.0,
    "min_price": 60.0,
    "category": "Audio",
    "brand": "LED Magic Ball Light",
    "color": "Base Negra / Cúpula Cristal",
    "features": "Parlante con bola de luces giratorias RGB que se mueven al ritmo de la música.",
    "power": "Enchufe directo 220V / USB",
    "instructions": "1. Enchufar. 2. Insertar Flash Memory o conectar vía Bluetooth. 3. Operar con control remoto.",
    "warnings": "No girar la bola plástica superior con la mano forzando el motor.",
    "fun_fact": "El sensor de micrófono interno ajusta el destello de la luz al ritmo del bajo.",
    "image": "assets/images/productos/oficial/05 - Luces Mágica con Parlante/05 - Luces Mágica con Parlante - arriba.jpg"
  },
  {
    "id": "6",
    "name": "Mouse Inalámbrico Tri-Modo",
    "price": 85.0,
    "min_price": 70.0,
    "category": "Tecnología",
    "brand": "BL112",
    "color": "Blanco (Milky White)",
    "features": "Mouse silencioso recargable con triple conexión (Receptor 2.4G + Bluetooth 1 y 2).",
    "power": "Batería recargable USB-C",
    "instructions": "1. Insertar receptor USB o cambiar switch a Bluetooth. 2. Seleccionar modo con botón de canal.",
    "warnings": "Usar sobre pad mouse para no desgastar los deslizadores inferiores.",
    "fun_fact": "Permite alternar de la Laptop de trabajo a la Tablet con presionar un botón.",
    "image": "assets/images/productos/oficial/06 - Mouse Inalámbrico Tri-Modo/06 - Mouse Inalámbrico Tri-Modo - Caja.jpg"
  },
  {
    "id": "7",
    "name": "Audifonos TWS ColorNow",
    "price": 75.0,
    "min_price": 50.0,
    "category": "Audio",
    "brand": "FlyTWS 2E (ColorNow)",
    "color": "Negro",
    "features": "Audífonos intraauditivos compactos con cancelación de ruido pasiva y toque táctil.",
    "power": "Batería Recargable (Estuche powerbank)",
    "instructions": "1. Cargar estuche al 100%. 2. Sacar para auto-encendido. 3. Toques táctiles para pausar/avanzar.",
    "warnings": "Mantener limpios los pines dorados de carga en la base del estuche.",
    "fun_fact": "Cuentan con encendido y conexión automática apenas abres la tapa del estuche.",
    "image": "assets/images/productos/oficial/07 -Audifonos TWS ColorNow/07 -Audifonos TWS ColorNow - 01.jpg"
  },
  {
    "id": "8",
    "name": "Audífonos SY-T2 Bluetooth & Wired Headset",
    "price": 130.0,
    "min_price": 100.0,
    "category": "Audio",
    "brand": "Pure SY-T2 (Herophone)",
    "color": "Blanco Mate",
    "features": "Diadema Bluetooth over-ear con almohadillas acolchadas y sonido HD.",
    "power": "Batería recargable USB-C",
    "instructions": "1. Mantener presionado botón de encendido. 2. Buscar 'SY-T2' en Bluetooth. 3. Ajustar tamaño.",
    "warnings": "Limpiar almohadillas con paño ligeramente húmedo; no doblar bruscamente.",
    "fun_fact": "Permite conexión vía cable AUX 3.5mm si te quedas sin batería.",
    "image": "assets/images/productos/oficial/08 - Audífonos SY-T2 Bluetooth - Wired Headset/08 - Audífonos SY-T2 Bluetooth - Wired Headset-clean.jpg"
  },
  {
    "id": "9",
    "name": "Calentador de Manos + PowerBank",
    "price": 90.0,
    "min_price": 80.0,
    "category": "Hogar",
    "brand": "Cute Pet (6000 mAh)",
    "color": "Celeste / Varios",
    "features": "Accesorio portátil 2 en 1: emite calor regulable y funciona como cargador portátil.",
    "power": "Batería recargable 6000 mAh",
    "instructions": "1. Mantener presionado para activar calor. 2. Conectar cable USB para cargar el celular.",
    "warnings": "No usar la función de calentador mientras estés cargando la batería en el enchufe.",
    "fun_fact": "Alcanza temperaturas reconfortantes entre 45°C y 55°C en solo 5 segundos.",
    "image": "assets/images/productos/oficial/09 - Calentador de Manos + PowerBank/09 - Calentador de Manos + PowerBank - manos.jpg"
  },
  {
    "id": "10",
    "name": "Audífonos TWS Ultrapods Pro",
    "price": 65.0,
    "min_price": 55.0,
    "category": "Audio",
    "brand": "Ultrapods Pro",
    "color": "Negro / Transparente",
    "features": "Earbuds TWS con estuche transparente futurista, pantalla digital de batería y luz LED.",
    "power": "Estuche de carga USB-C",
    "instructions": "1. Cargar el estuche. 2. Sacar ambos earbuds. 3. Conectar al celular por Bluetooth.",
    "warnings": "Evitar caídas del estuche acrílico para no rayar o fisurar la transparencia.",
    "fun_fact": "Muestra el porcentaje exacto de batería restante en número digital dentro del estuche.",
    "image": "assets/images/productos/oficial/10 - Audífonos TWS Ultrapods Pro/10 - Audífonos TWS Ultrapods Pro - 01.jpg"
  },
  {
    "id": "11",
    "name": "Bola de burbuja solar Cadena de luz LED Bola de cristal",
    "price": 50.0,
    "min_price": 45.0,
    "category": "Decoración / Regalos",
    "brand": "Esféricas tipo Burbuja",
    "color": "Transparente / Cable Negro",
    "features": "Luces de exterior cálidas/multicolor con focos tipo gota/burbuja acrílica.",
    "power": "Panel Solar",
    "instructions": "1. Fijar panel solar donde reciba luz directa. 2. Activar interruptor posterior. 3. Colgar guirnalda.",
    "warnings": "El panel debe recibir al menos 6 horas de sol directo para brillar toda la noche.",
    "fun_fact": "El acrílico burbuja es ultra resistente a caídas y granizo leve.",
    "image": "assets/images/productos/oficial/11 - Bola de burbuja solar luz Led/11 - Bola de burbuja solar luz Led - 01.jpg"
  },
  {
    "id": "12",
    "name": "Parlante Bluetooth Compacto - X1 Music Engine 3202",
    "price": 70.0,
    "min_price": 35.0,
    "category": "Audio",
    "brand": "MOIC Wireless X",
    "color": "Rosado / Gris",
    "features": "Parlante portátil de diseño juvenil con agarrador integrado y rejilla protectora.",
    "power": "Batería recargable USB",
    "instructions": "1. Encender parlante. 2. Conectar mediante Bluetooth o cable AUX/USB. 3. Ajustar volumen.",
    "warnings": "Evitar caídas e impactos fuertes en el cono del parlante.",
    "fun_fact": "Incorpora radio FM integrada mediante la conexión del cable de carga como antena.",
    "image": "assets/images/productos/oficial/12 - Parlante Bluetooth Compacto - X1 Music Engine 3202/12 - Parlante Bluetooth Compacto - 01.jpg"
  },
  {
    "id": "13",
    "name": "Muñeco de Nieve LED Solar",
    "price": 45.0,
    "min_price": 35.0,
    "category": "Decoración / Regalos",
    "brand": "Adorno Navideño",
    "color": "Blanco / Rosa",
    "features": "Figura decorativa de jardín estilo cristal con sombrero rosa/rojo.",
    "power": "Panel Solar en estaca",
    "instructions": "1. Ensamble de estaca. 2. Activar botón ON. 3. Clavar en maceta o césped.",
    "warnings": "Guardar bajo techo en tormentas extremas.",
    "fun_fact": "El cuerpo cristalino difumina la luz creando un brillo omnidireccional.",
    "image": "assets/images/productos/oficial/13 - Muñeco de Nieve LED Solar/13 - Muñeco de Nieve LED Solar - 01.jpg"
  },
  {
    "id": "14",
    "name": "Audífonos On-Ear Q50",
    "price": 50.0,
    "min_price": 80.0,
    "category": "Audio",
    "brand": "Q50 (Microlab)",
    "color": "Rojo",
    "features": "Diadema acolchada roja con micrófono integrado para llamadas y música.",
    "power": "Batería recargable USB / AUX",
    "instructions": "1. Encender botón power. 2. Buscar en Bluetooth o conectar cable AUX. 3. Ajustar volumen.",
    "warnings": "Guardar en estuche para evitar rozaduras en el acabado brillante.",
    "fun_fact": "Su estructura es plegable hacia adentro para ocupar la mitad del espacio.",
    "image": "assets/images/productos/oficial/14 - Audífonos On-Ear Q50/14 - Audífonos On-Ear Q50 - 01.jpg"
  },
  {
    "id": "15",
    "name": "Audífonos Inalámbricos Deportivos",
    "price": 55.0,
    "min_price": 45.0,
    "category": "Audio",
    "brand": "i10 Neckband Earbuds",
    "color": "Negro / Gris metálico",
    "features": "Audífonos de cuello flexibles IPX5 anticaída con cabezales magnéticos.",
    "power": "Batería recargable USB",
    "instructions": "1. Colocar la banda sobre la nuca. 2. Insertar gomas en los oídos. 3. Encender y conectar.",
    "warnings": "No tirar con fuerza de los cables delgados de las gomas.",
    "fun_fact": "Los earbuds se unen entre sí por imán para que no bamboleen cuando no los usas.",
    "image": "assets/images/productos/oficial/15 - Audífonos Inalámbricos Deportivos/15 - Audífonos Inalámbricos Deportivos - 01.jpg"
  },
  {
    "id": "16",
    "name": "Smartwatch Phone Cuadrado",
    "price": 100.0,
    "min_price": 75.0,
    "category": "Tecnología",
    "brand": "Smart Watch Phone",
    "color": "Negro",
    "features": "Reloj inteligente con ranura SIM (hace llamadas), cámara, monitor de pasos y Bluetooth.",
    "power": "Batería interna recargable",
    "instructions": "1. Insertar chip SIM / MicroSD. 2. Encender e instalar app. 3. Vincular vía Bluetooth.",
    "warnings": "Cargar con cable USB; NO es sumergible en agua.",
    "fun_fact": "Funciona tanto de forma independiente (con SIM) como de accesorio del celular.",
    "image": "assets/images/productos/oficial/16 - Smartwatch Phone Cuadrado/16 - Smartwatch Phone Cuadrado - 01.jpg"
  },
  {
    "id": "17",
    "name": "Reloj Despertador Digital LED",
    "price": 45.0,
    "min_price": 35.0,
    "category": "Hogar",
    "brand": "MoodiCare Clock",
    "color": "Blanco (Luz LED multicolor)",
    "features": "Reloj cubo digital con hora, fecha, temperatura y cambio de color progresivo.",
    "power": "3 pilas AAA (Luces) / 2 LR44 (Pantalla)",
    "instructions": "1. Colocar pilas. 2. Configurar hora con botones SET/UP/DOWN. 3. Presionar arriba para luz.",
    "warnings": "Evitar caídas fuertes que descalibren la pantalla LCD.",
    "fun_fact": "Utiliza cromoterapia básica (cambio de luz suave) para ayudar a conciliar el sueño.",
    "image": "assets/images/productos/oficial/17 - Reloj Despertador Digital LED/17 - Reloj Despertador Digital LED - 01.jpg"
  },
  {
    "id": "18",
    "name": "Parlante Bluetooth para Ducha",
    "price": 35.0,
    "min_price": 35.0,
    "category": "Audio",
    "brand": "Waterproof Shower Speaker",
    "color": "Blanco / Azul",
    "features": "Parlante Bluetooth con ventosa de sujeción resistente a salpicaduras y vapor.",
    "power": "Batería recargable Micro-USB",
    "instructions": "1. Cargar puerto. 2. Pegar ventosa en azulejo/vidrio. 3. Vincular celular por Bluetooth.",
    "warnings": "Resistente a salpicaduras, pero NO sumergible bajo el agua.",
    "fun_fact": "Incluye botones integrados para contestar llamadas en manos libres.",
    "image": "assets/images/productos/oficial/18 - Parlante Bluetooth para Ducha/18 - Parlante Bluetooth para Ducha - 01.jpg"
  },
  {
    "id": "19",
    "name": "Lámpara LED 3D Ilusión Óptica",
    "price": 50.0,
    "min_price": 50.0,
    "category": "Decoración / Regalos",
    "brand": "3D Illusion Lamp",
    "color": "Negro (Base) / Acrílico",
    "features": "Lámpara de noche con placa acrílica que genera efecto visual 3D al encenderse.",
    "power": "Cable USB 5V o 3 pilas AA",
    "instructions": "1. Retirar film protector del acrílico. 2. Insertar placa en la base. 3. Encender por botón táctil.",
    "warnings": "Quitar el film protector antes de usar; no tocar el acrílico para no dejar huellas.",
    "fun_fact": "La placa es completamente plana (2D), pero el grabado engaña al cerebro simulando 3D.",
    "image": "assets/images/productos/oficial/19 - Lámpara LED 3D Ilusión Óptica/19 - Lámpara LED 3D Ilusión Óptica - 01.jpg"
  },
  {
    "id": "20",
    "name": "Lámpara de Mesa Cristal (Diamante)",
    "price": 95.0,
    "min_price": 80.0,
    "category": "Hogar",
    "brand": "Diamond Table Lamp",
    "color": "Dorado / Cristal transparente",
    "features": "Lámpara táctil con efecto óptico de destellos de diamante en cristal acrílico.",
    "power": "Batería recargable USB",
    "instructions": "1. Cargar vía USB. 2. Tocar la parte superior dorada para encender y cambiar tonos.",
    "warnings": "Limpiar con paño de microfibra seco para evitar rayones en el acrílico.",
    "fun_fact": "El grabado geométrico proyecta una rosa o estrella de luz a su alrededor.",
    "image": "assets/images/productos/oficial/20 - Lámpara de Mesa Cristal (Diamante)/20 - Lámpara de Mesa Cristal (Diamante) - 01.jpg"
  },
  {
    "id": "21",
    "name": "Guirnalda LED Balones de Fútbol",
    "price": 40.0,
    "min_price": 25.0,
    "category": "Decoración / Regalos",
    "brand": "Balones de Fútbol Americano",
    "color": "Marrón / Ámbar",
    "features": "Tira de luces LED decorativas con forma de balones deportistas.",
    "power": "2 o 3 pilas AA",
    "instructions": "1. Insertar pilas en la cajita. 2. Cambiar interruptor a ON o modo parpadeo.",
    "warnings": "Uso preferente en interiores (caja de pilas no sumergible).",
    "fun_fact": "Los LED consumen tan poco que un par de pilas dura semanas encendido.",
    "image": "assets/images/productos/oficial/21 - Guirnalda LED Balones de Futbol/21 - Guirnalda LED Balones de Futbol - 01.jpg"
  },
  {
    "id": "22",
    "name": "Mouse Gamer G305 (Genérico)",
    "price": 140.0,
    "min_price": 120.0,
    "category": "Tecnología",
    "brand": "G305 Lightspeed (Logitech)",
    "color": "Blanco",
    "features": "Mouse Gamer Profesional Inalámbrico con sensor HERO de 12.000 DPI y cero latencia.",
    "power": "1 Pila AA (Hasta 250 horas)",
    "instructions": "1. Insertar pila AA. 2. Conectar receptor USB a la PC. 3. Descargar Logitech G HUB (opcional).",
    "warnings": "Limpiar sensor óptico con aire comprimido o hisopo seco.",
    "fun_fact": "El sensor HERO consume 10 veces menos energía que sensores anteriores.",
    "image": "assets/images/productos/oficial/22 - Mouse Gamer G305 (Genérico)/22 - Mouse Gamer G305 (Genérico) - 01.jpg"
  },
  {
    "id": "23",
    "name": "Parlante Portátil (Clip 3 Estilo)",
    "price": 75.0,
    "min_price": 50.0,
    "category": "Audio",
    "brand": "Clip 3 (Estilo JBL)",
    "color": "Azul Oscuro",
    "features": "Parlante ultra portátil con mosquetón metálico integrado para colgar en mochilas.",
    "power": "Batería recargable USB",
    "instructions": "1. Enganchar en mochila/cinturón. 2. Encender y vincular por Bluetooth. 3. Ajustar volumen.",
    "warnings": "No mojar en exceso si la tapa del puerto de carga está abierta.",
    "fun_fact": "El marco de mosquetón rodea todo el perímetro del parlante dándole rigidez.",
    "image": "assets/images/productos/oficial/23 - Parlante Portátil (Clip 3 Estilo)/23 - Parlante Portátil (Clip 3 Estilo) - 01.jpg"
  },
  {
    "id": "24",
    "name": "Extractor de Leche Materna",
    "price": 65.0,
    "min_price": 45.0,
    "category": "Hogar",
    "brand": "Nobel",
    "color": "Celeste / Transparente",
    "features": "Extractor ergonómico con palanca, cojín de silicona y biberón de 180 ml libre de BPA.",
    "power": "Manual (Sin baterías)",
    "instructions": "1. Esterilizar componentes. 2. Adherir copa al pecho. 3. Presionar la palanca rítmicamente.",
    "warnings": "Lavar y esterilizar en agua hirviendo después de cada uso.",
    "fun_fact": "El diseño de la copa imita la succión natural del bebé para estimular la leche.",
    "image": "assets/images/productos/oficial/24 - Extractor de Leche Materna/24 - Extractor de Leche Materna - 01.jpg"
  },
  {
    "id": "25",
    "name": "Reflector Solar LED IP66",
    "price": 220.0,
    "min_price": 180.0,
    "category": "Hogar",
    "brand": "Private Street Lamp IP66",
    "color": "Naranja y Negro",
    "features": "Proyector de alta potencia para exteriores IP66 con panel solar independiente.",
    "power": "Panel Solar + Batería LiFePO4",
    "instructions": "1. Montar reflector y panel en pared. 2. Conectar cable entre panel y reflector. 3. Configurar con control remoto.",
    "warnings": "No cubrir el panel con ramas ni techos.",
    "fun_fact": "Incluye sensor de movimiento y temporizador mediante control remoto.",
    "image": "assets/images/productos/oficial/25 - Reflector Solar LED IP66/25 - Reflector Solar LED IP66 - 01.jpg"
  },
  {
    "id": "26",
    "name": "Lienzo / Tapiz Navideño LED",
    "price": 45.0,
    "min_price": 45.0,
    "category": "Decoración / Regalos",
    "brand": "Muñeco de Nieve con Iluminación",
    "color": "Multicolor",
    "features": "Cuadro de tela estampado con luces LED integradas en el diseño.",
    "power": "2 pilas AA",
    "instructions": "1. Colocar pilas en el reverso. 2. Colgar en la pared. 3. Activar el interruptor lateral.",
    "warnings": "No lavar con agua ni doblar bruscamente para no romper los cables internos.",
    "fun_fact": "Los LED están colocados estratégicamente en las luces de los árboles y estrellas.",
    "image": "assets/images/productos/oficial/26 - Lienzo - Tapiz Navideño LED/26 - Lienzo - Tapiz Navideño LED - 01.jpg"
  },
  {
    "id": "27",
    "name": "Mouse Inalámbrico Ergonómico",
    "price": 50.0,
    "min_price": 35.0,
    "category": "Tecnología",
    "brand": "QC Pass Geometric Mouse",
    "color": "Negro Mate",
    "features": "Mouse inalámbrico compacto con diseño geométrico texturizado antideslizante.",
    "power": "1 o 2 pilas AAA",
    "instructions": "1. Abrir tapa e insertar pilas. 2. Conectar nanoreceptor USB a la PC. 3. Usar directamente.",
    "warnings": "Apagar el switch inferior al guardar en la mochila para ahorrar pila.",
    "fun_fact": "Guardado interno: el receptor USB se almacena dentro del compartimento de pilas.",
    "image": "assets/images/productos/oficial/27 - Mouse Inalámbrico Ergonómico/27 - Mouse Inalámbrico Ergonómico - 01.jpg"
  },
  {
    "id": "28",
    "name": "Lámpara Solar Conmemorativa",
    "price": 65.0,
    "min_price": 55.0,
    "category": "Decoración / Regalos",
    "brand": "Cruz con Rosas en Piedra",
    "color": "Gris Piedra / Rosas Rosas",
    "features": "Piedra decorativa solar con cruz y flores para lápidas o jardines conmemorativos.",
    "power": "Panel Solar integrado",
    "instructions": "1. Presionar botón inferior. 2. Ubicar en exterior soleado.",
    "warnings": "Limpiar la superficie del panel para evitar acumulación de tierra.",
    "fun_fact": "Diseñada en resina sintética que imita piedra real para resistir la intemperie.",
    "image": "assets/images/productos/oficial/28 - Lampara Solar Conmemorativa/28 - Lampara Solar Conmemorativa - 01.jpg"
  },
  {
    "id": "29",
    "name": "Cortador de Vellos Nasales",
    "price": 40.0,
    "min_price": 30.0,
    "category": "Cuidado Personal",
    "brand": "AE-3802",
    "color": "Gris Oscuro / Negro",
    "features": "Recortador de bolsillo para vellos de nariz y orejas con cuchillas redondas seguras.",
    "power": "1 Pila AA",
    "instructions": "1. Insertar pila AA. 2. Encender switch. 3. Introducir suavemente en fosas nasales u oídos.",
    "warnings": "No lavar el cuerpo entero bajo el grifo; desmontar solo el cabezal de corte.",
    "fun_fact": "Las cuchillas giran 360° internamente dentro de un escudo para proteger la piel.",
    "image": "assets/images/productos/oficial/29 - Cortador de Vellos Nasales/29 - Cortador de Vellos Nasales - 01.jpg"
  },
  {
    "id": "30",
    "name": "Mouse Gamer RGB (X9)",
    "price": 75.0,
    "min_price": 50.0,
    "category": "Tecnología",
    "brand": "X9 Game Mouse",
    "color": "Negro",
    "features": "Mouse ergonómico con sensor óptico de alta precisión, botones laterales y luces RGB.",
    "power": "Batería recargable USB",
    "instructions": "1. Conectar receptor USB a la PC. 2. Encender switch inferior. 3. Ajustar DPI con botón superior.",
    "warnings": "Evitar caídas que desalineen el sensor óptico inferior.",
    "fun_fact": "El botón DPI altera la velocidad del puntero al instante sin ir a configuración de la PC.",
    "image": "assets/images/productos/oficial/30 - Mouse Gamer RGB (X9)/30 - Mouse Gamer RGB (X9) - 01.jpg"
  },
  {
    "id": "31",
    "name": "Cortadora de Barba T9 Vintage",
    "price": 90.0,
    "min_price": 70.0,
    "category": "Cuidado Personal",
    "brand": "Vintage T9 Professional",
    "color": "Negro (Grabado Dragón)",
    "features": "Máquina recortadora de barba y contornos con cuerpo metálico grabado y cuchilla en T.",
    "power": "Batería recargable USB",
    "instructions": "1. Encender botón inferior. 2. Colocar peine guía si se desea. 3. Recortar al ras.",
    "warnings": "Aceitar las cuchillas regularmente y limpiar pelusa con el cepillo incluido.",
    "fun_fact": "Su cabezal en T permite hacer líneas perfectas en patillas y cuello como de barbería.",
    "image": "assets/images/productos/oficial/31 - Cortadora de Barba T9 Vintage/31 - Cortadora de Barba T9 Vintage - 01.jpg"
  },
  {
    "id": "32",
    "name": "Mini Parlante M3 Metalizado",
    "price": 45.0,
    "min_price": 35.0,
    "category": "Audio",
    "brand": "M3 Pairable Wireless Speaker",
    "color": "Azul Metalizado / Degradé",
    "features": "Mini parlante ultra portátil en cuerpo de aluminio con sonido potente.",
    "power": "Batería recargable USB",
    "instructions": "1. Encender botón inferior. 2. Buscar \"M3\" en el Bluetooth del celular. 3. Reproducir.",
    "warnings": "Cargar con adaptadores estándar de 5V 1A.",
    "fun_fact": "Se pueden emparejar dos parlantes M3 al mismo celular para sonido estéreo TWS.",
    "image": "assets/images/productos/oficial/32 - Mini Parlante M3 Metalizado/32 - Mini Parlante M3 Metalizado - 01.jpg"
  },
  {
    "id": "33",
    "name": "Timbre Inteligente con Cámara",
    "price": 150.0,
    "min_price": 120.0,
    "category": "Seguridad / Domótica",
    "brand": "X9 Visuable Smart Doorbell",
    "color": "Blanco con frontal negro",
    "features": "Timbre inalámbrico con cámara, audio bidireccional y notificación al celular.",
    "power": "Batería recargable USB / Chime a corriente",
    "instructions": "1. Fijar timbre en puerta principal. 2. Enchufar timbre receptor dentro de casa. 3. Sincronizar app.",
    "warnings": "Proteger de lluvia directa prolongada si la entrada no tiene alero.",
    "fun_fact": "Permite distorsionar la voz en tiempo real para mayor seguridad en la llamada.",
    "image": "assets/images/productos/oficial/33 - Timbre Inteligente con Cámara/33 - Timbre Inteligente con Cámara - 01.jpg"
  },
  {
    "id": "34",
    "name": "Luz Nocturna LED con Sensor",
    "price": 60.0,
    "min_price": 30.0,
    "category": "Hogar",
    "brand": "Intelligent Night Light",
    "color": "Blanco",
    "features": "Luz automática magnética que se enciende al detectar movimiento en la oscuridad.",
    "power": "Batería recargable USB / Magnético",
    "instructions": "1. Pegar base magnética en la pared. 2. Adherir la lámpara. 3. Cambiar a modo AUTO.",
    "warnings": "Solo funciona en ambientes oscuros para ahorrar energía.",
    "fun_fact": "Apagado automático a los 15-20 segundos de no detectar movimiento.",
    "image": "assets/images/productos/oficial/34 - Luz Nocturna LED con Sensor/34 - Luz Nocturna LED con Sensor - 01.jpg"
  },
  {
    "id": "35",
    "name": "Calentador y Esterilizador (Disney)",
    "price": 180.0,
    "min_price": 160.0,
    "category": "Hogar",
    "brand": "EL-957A (Disney Baby)",
    "color": "Rosado / Blanco",
    "features": "Calentador eléctrico para mamaderas y esterilizador al vapor con perilla de control.",
    "power": "Enchufe directo 220V AC",
    "instructions": "1. Colocar agua en la base. 2. Poner biberón o chupón. 3. Girar perilla a temperatura deseada.",
    "warnings": "Nunca encender sin agua en el depósito inferior para no quemar la resistencia.",
    "fun_fact": "Mantiene el biberón tibio a 40°C automáticamente durante toda la noche.",
    "image": "assets/images/productos/oficial/35 - Calentador y Esterilizador (Disney)/35 - Calentador y Esterilizador (Disney) - 01.jpg"
  },
  {
    "id": "36",
    "name": "Radio Reproductor Portátil",
    "price": 80.0,
    "min_price": 150.0,
    "category": "Audio",
    "brand": "LT-IPHONE 6 (Leotec)",
    "color": "Negro",
    "features": "Radio multibanda (FM/AM/SW), reproductor USB/SD, Bluetooth y linterna.",
    "power": "220V AC / Batería recargable / Pilas D",
    "instructions": "1. Seleccionar modo (BT/Radio/USB). 2. Sintonizar perilla analógica. 3. Extender antena telescópica.",
    "warnings": "Desconectar de la corriente una vez cargado si se usa en modo batería.",
    "fun_fact": "El nombre \"LT-IPHONE 6\" es una marca fantasía vintage comercializada por el fabricante.",
    "image": "assets/images/productos/oficial/36 - Radio Reproductor Portátil/36 - Radio Reproductor Portátil - 01.jpg"
  },
  {
    "id": "37",
    "name": "Antena Digital HDTV",
    "price": 45.0,
    "min_price": 30.0,
    "category": "Tecnología",
    "brand": "Hochauflösende TV-Antenne",
    "color": "Negro",
    "features": "Antena de alta ganancia omnidireccional para captar canales de televisión digital abierta.",
    "power": "Conexión coaxial / USB (amplificador)",
    "instructions": "1. Conectar cable a la TV. 2. Pegar base magnética en ventana o metal. 3. Buscar canales.",
    "warnings": "Colocar lo más cerca posible de ventanas para mejor recepción de señal.",
    "fun_fact": "Su base imantada permite fijarla firmemente a protecciones metálicas de ventanas.",
    "image": "assets/images/productos/oficial/37 - Antena Digital HDTV/37 - Antena Digital HDTV - 01.jpg"
  },
  {
    "id": "38",
    "name": "Audífonos TWS In-Ear (Pro Genérico)",
    "price": 50.0,
    "min_price": 35.0,
    "category": "Audio",
    "brand": "Pro (Earbuds TWS)",
    "color": "Negro Brillante",
    "features": "Earbuds ergonómicos negros con caja compacta de bolsillo.",
    "power": "Estuche de carga USB",
    "instructions": "1. Sacar los audífonos. 2. Vincular por Bluetooth. 3. Colocar en el oído.",
    "warnings": "Limpiar gomas de silicona frecuentemente por higiene.",
    "fun_fact": "Tienen estuche con ajuste imantado que atrae los earbuds a su posición de carga.",
    "image": "assets/images/productos/oficial/38 - Audífonos TWS In-Ear (Pro Genérico)/38 - Audífonos TWS In-Ear (Pro Genérico) - 01.jpg"
  },
  {
    "id": "39",
    "name": "Mini Ventilador de Bolsillo",
    "price": 38.0,
    "min_price": 30.0,
    "category": "Hogar",
    "brand": "Pocket Fan",
    "color": "Blanco (con orejitas)",
    "features": "Ventilador de mano compacto con orejitas animadas y base para escritorio.",
    "power": "Batería recargable USB",
    "instructions": "1. Cargar por USB. 2. Presionar botón frontal para encender. 3. Ajustar velocidades.",
    "warnings": "No meter los dedos ni objetos en la rejilla mientras gira.",
    "fun_fact": "Incluye base desmontable para colocarlo como ventilador de escritorio.",
    "image": "assets/images/productos/oficial/39 - Mini Ventilador de Bolsillo/39 - Mini Ventilador de Bolsillo - 01.jpg"
  },
  {
    "id": "40",
    "name": "Proyector de Luces LED - Varios",
    "price": 65.0,
    "min_price": 60.0,
    "category": "Decoración / Regalos",
    "brand": "LED Projection Light",
    "color": "Negro (Proyección Multicolor)",
    "features": "Proyector de figuras en movimiento (calabazas, fantasmas, murciélagos).",
    "power": "Enchufe directo 110-220V",
    "instructions": "1. Conectar a la corriente. 2. Apuntar hacia pared o fachada. 3. Ajustar distancia para enfocar.",
    "warnings": "Evitar mirar fijamente la lente de proyección activa.",
    "fun_fact": "Cubre hasta 50 metros cuadrados si se aleja a una distancia de 5 metros.",
    "image": "assets/images/productos/oficial/40 - Proyector de Luces LED - Varios/40 - Proyector de Luces LED - Varios - 01.jpg"
  },
  {
    "id": "41",
    "name": "Buclera Enruladora Rizadora",
    "price": 30.0,
    "min_price": 20.0,
    "category": "Cuidado Personal",
    "brand": "Varios",
    "color": "Varios",
    "features": "Productos con fallas por transporte o devueltos malogrados.",
    "power": "N/A",
    "instructions": "N/A",
    "warnings": "Vender sin garantía declarando fallas.",
    "fun_fact": "Recuperar monetario de mercadería dañada.",
    "image": "assets/images/productos/oficial/41 - Buclera Enruladora Rizadora/41 - Buclera Enruladora Rizadora - 01.jpg"
  }
];
